### ISSUE TITLE
Error during loading jce_policy

### ISSUE THREAD

**Issue by BorisInGitHub** [flexiondotorg/oab-java6#109] opened 2013-07-23 08:39 UTC
[x] Installing Java build requirements success
 [x] Making build directories success
 [x] Updating from https://github.com/rraptorr/sun-java6 success
 [x] Removing local clones of sun-java6 success
 [x] Cloning sun-java6 with v6.45-1 success
 [x] Getting Java SE download page success
 [x] Getting current release download page success
 [x] Getting previous releases download page success
 [x] Downloading jdk-6u45-linux-i586.bin : 68.47 MB success
 [x] Symlinking jdk-6u45-linux-i586.bin success
 [x] Downloading jdk-6u45-linux-x64.bin : 68.75 MB success
 [x] Symlinking jdk-6u45-linux-x64.bin success
 [x] Getting Java Cryptography Extension download page success
 [x] Downloading jce_policy-6.zip :  failed
 [i] Showing the last 5 lines from the logfile (/home/breynard/oab-java.sh.log)...
 [x] Downloading jce_policy-6.zip :    --2013-07-23 10:35:47--  http://jce_policy-6.zip/
Résolution de jce_policy-6.zip (jce_policy-6.zip)... échec: Aucun fichier ou dossier de ce type.
wget : impossible de résoudre l'adresse de l'hôte «jce_policy-6.zip»
7292's retcode: 4
failed

**Comment by Boboss74** [comment] 2013-07-26 12:36
Duplicate of #101.

**Comment by alfetopito** [comment] 2013-08-12 06:23
got the same here

**Comment by flexiondotorg** [comment] 2013-09-05 09:44
Merged pull-requuest #111.

**Closed as completed by flexiondotorg** 2013-09-05 09:44 UTC
