### ISSUE TITLE
error: gnutls_handshake() failed: An unexpected TLS packet was received on running script

### ISSUE THREAD

**Issue by johndeverall** [flexiondotorg/oab-java6#116] opened 2013-09-23 02:31 UTC
- http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

 tail -f /home/john/Downloads/oab-java.sh.log

 [x] Installing Java build requirementssuccess
 [x] Making build directoriessuccess
 [x] Mirroring https://github.com/rraptorr/sun-java6failed
 [i] Showing the last 5 lines from the logfile (/home/john/Downloads/oab-java.sh.log)...
 [x] Mirroring https://github.com/rraptorr/sun-java6  Cloning into bare repository 'sun-java6.git'...
error: gnutls_handshake() failed: An unexpected TLS packet was received. while accessing https://github.com/rraptorr/sun-java6/info/refs
fatal: HTTP request failed
27109's retcode: 128
failed

**Comment by johndeverall** [comment] 2013-09-23 02:32
Just wondering if any of you guys can give me a heads up what might be causing it? :)

**Comment by gayle** [comment] 2013-10-03 20:10
I am wondering the same thing. I was getting a similar error, and a Google search brought me here.  My output: 

---

$ sudo ./oab-java.sh
[sudo] password for n592724: 
oab-java.sh v0.2.6 - Create a local 'apt' repository for Sun Java 6 and/or Oracle Java 7 packages.

Copyright (c) Martin Wimpress, http://flexion.org. MIT License

By running this script to download Java you acknowledge that you have
read and accepted the terms of the Oracle end user license agreement.
- http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

  tail -f /home/n592724/oab-java.sh.log

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 failed
 [i] Showing the last 5 lines from the logfile (/home/n592724/oab-java.sh.log)...
 [x] Cloning https://github.com/rraptorr/sun-java6   Cloning into 'src'...
error: Failed connect to github.com:443; Connection timed out while accessing https://github.com/rraptorr/sun-java6/info/refs
fatal: HTTP request failed
15898's retcode: 128
failed

---

I know this is similar to https://github.com/flexiondotorg/oab-java6/issues/32 which says it was fixed in version 0.2.4.  I am using version 0.2.6, so it seems like the issue should still be fixed in that version.  I'm also using Ubuntu 12.10, if that information helps at all.

Yet if I go to https://github.com/rraptorr/sun-java6/info/refs in a browser (on the same machine where I'm running the shell script, or on any other machine) I am getting a 404 error for that URL.  I can go to other URLs, even https://github.com/rraptorr/sun-java6/, on that machine without a problem.  Just not https://github.com/rraptorr/sun-java6/info/refs

What to do? 

Thanks!

**Comment by flexiondotorg** [comment] 2014-01-06 16:57
This was caused by a GitHub outage.

**Closed as completed by flexiondotorg** 2014-01-06 16:57 UTC
